Expand beta process to perform all actions - compile, publish
checkdigit/github-actions pull request #13
Opened 2022-10-05 00:46 UTC by adcreare

Closes https://github.com/checkdigit/github-actions/issues/12

2022-10-06 18:27 UTC, carlansley requested changes
nice, like it.  just one minor comment.

2022-10-07 05:10 UTC, adcreare commented on src/publish-beta/command.ts
> +  log('Action starts:command');
Yup - agreed

2022-10-10 22:26 UTC, adcreare commented
Bunch of fixes
- Removed command file completely
- src folder is now included in package (I also parse the package.json files property and add /src/ there if it doesn't exist
- src folder is cleaned so only .ts files and swagger.yml files exist (exclusing everything else including .test.ts and .spec.ts files)

Ready for another look.

2022-10-12 17:53 UTC, carlansley requested changes
lgtm, one minor issue re the logging

2022-10-12 17:53 UTC, carlansley commented on src/publish-beta/compile.ts
> +const log = debug('action:compile');
I think all the debug namespaces should be prefixed by the name of the action, e.g. `publish-beta:compile`

2022-10-13 01:31 UTC, adcreare commented
Yup! Done - ready for another look

2022-10-13 02:05 UTC, carlansley approved these changes

2022-10-13 02:06 UTC, merged