added package denier action
checkdigit/github-actions pull request #22
Opened 2022-11-28 18:43 UTC by lukebrdn

Resolves #21

2022-11-29 07:55 UTC, adcreare requested changes
Looks good - few minor things

2022-11-29 07:55 UTC, adcreare commented on src/package-denier/package-lock-file-util.ts
> +function compareSemverVersions(version1: string, version2: string): number {
would it make sense to use the npm semver package here? https://github.com/npm/node-semver - as its made by the NPM people its probably going to get updates for any additional operators they add? It includes a comparison operator

2022-11-29 07:55 UTC, adcreare commented on src/package-denier/rules.ts
> +const rules: Rule[] = [['@aws-sdk/client-*', '>', '3.1.0']];
Should be `3.193.0` I believe thats the last version we've had live without issues inside aws-nock. 
Also should add:
* `got > 11.8.5` 
* `get-port > 5.1.1`
* `antlr4 > 4.9.3`
* `@aws-sdk/credential-provider-ini > 3.193.0`
* `@aws-sdk/credential-provider-node > 3.193.0`
* `@aws-sdk/smithy-client > 3.193.0`
* `@aws-sdk/types >  3.193.0`

2022-12-05 03:22 UTC, adcreare approved these changes
LGTM

2022-12-19 19:35 UTC, carlansley approved these changes
lgtm

2022-12-19 19:35 UTC, merged