Prevent spec.mjs from being bundled
checkdigit/github-actions pull request #42
Opened 2023-05-19 03:40 UTC by adcreare

Closes https://github.com/checkdigit/github-actions/issues/41

2023-05-19 15:35 UTC, carlansley requested changes

2023-05-19 15:35 UTC, carlansley commented on src/publish-beta/files.ts
> +      if (item.name.endsWith('.spec.ts') || item.name.endsWith('.test.ts') || item.name.endsWith('.spec.mts')) {
also `.test.mts`

2023-05-22 03:10 UTC, adcreare commented
Ready for another look!

2023-05-22 04:01 UTC, carlansley approved these changes

2023-05-24 03:41 UTC, merged